### ISSUE TITLE
[BUG] sort by due date not functioning

### ISSUE THREAD

**Issue by RLP1369** [pgorod/power-todoist-card#18]
Is the sort by due date functionality no longer working?  I have followed all steps…I have selected “true”, “ascending” and “descending”, none of which impact the list.

TIA

**Comment by pgorod** [comment]
Are you also using anything from the ["Filtering by Dates" section of the Docs](https://github.com/pgorod/power-todoist-card#filtering-by-dates)?

Are you using any other sorting option at the same time, that might be interfering?

You probably need to share more of your configuration so I can try and reproduce here. If you can create a [Minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) that would be ideal. Thanks

**Comment by RLP1369** [comment]
Thank you for the prompt response!!  I have several items on the list, but only one has a due date, so I’m not sure if this is part of the issue.
I also sorted the list inside of the Todoist app, and the HA card is not picking up the “updated” sort from Todoist.  This was done after not having success with the “sort by due date”.
Here is my code:

type: custom:powertodoist-card
entity: sensor.to_do_list
layout_options:
  grid_columns: 1
  grid_rows: 5
show_header: false
show_completed: 0
sort_by_due_date: ascending
show_item_add: false
show_item_close: true
show_item_delete: false
filter_today_overdue: false
card_mod:
  style: |
    ha-card {
      color: grey;
    }

**Comment by RLP1369** [comment]
I finally resolved the issue.  I removed all items from the list, set the sort by parameter and repopulated the list.  All is working now!
