### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by crowe83** [pgorod/power-todoist-card#7]
**Before submitting a bug**
- [X] I updated to the latest card version available
- [X] I cleared the cache of my browser

**Describe the bug**
Card no longer displays any tasks. The card displays the message "Sensors don't have any data yet. Please wait a few seconds and refresh". In the past it has shown "No uncompleted tasks" when there are no tasks that fit the filters. Even clearing all filters from the card gets the error. Seems to coincide with the latest version of home assistant.

**To Reproduce**
Add the card to a dashboard

**Expected behavior**
Show tasks

**Screenshots**

**Versions:**
 - Card: [v0.11-beta]
 - HomeAssistant: [2023.12.1]
 - Browser: [Safari 19616.2.9.11.7] + [Chrome 119.0.6045.159}

**Additional context**
The sensor seems to still be getting the same data (i.e. project, items)

**Comment by pgorod** [comment]
You probably need to do this procedure with the new Hass version:

https://community.home-assistant.io/t/powertodoist-card-lists-kanbans-and-much-more-beta-release/583251/41?u=pgr

**Comment by crowe83** [comment]
That worked great. Thank you!
