### ISSUE TITLE
[BUG] Invalid config when try to add sensor

### ISSUE THREAD

**Issue by julienvedebe** [pgorod/power-todoist-card#9]
**Before submitting a bug**
- [X] I updated to the latest card version available
- [X] I cleared the cache of my browser

**Describe the bug**
When I try to add the sensor REST part in my sensors.yaml : 

- platform: rest
  method: GET
  resource: "https://api.todoist.com/sync/v9/projects/get_data"
  name: "Ma todo"
  params:
    project_id: perso-2315329691
    headers: "Authorization: Bearer XXXX"
    value_template: "{{ value_json['project']['id'] }}"
    json_attributes:
      - project
      - items
      - sections
      - project_notes
    scan_interval: 30

I got an error in the configuration validation : Invalid config for 'rest' from integration 'sensors' at sensors.yaml, line 51: template valiue should be a string for dictionary value 'params->json_attributes', got ['project','items','sections','project_notes']

**To Reproduce**
1. Go to an editor
2. Paste code below
3. Go to dev tool
4. Try to check the configuration

**Versions:**
 - Card: [v0.11-beta]
 - HomeAssistant: [2024.3.3]
 - Browser: Version 123.0.6312.59 (Build officiel) (arm64)

Thanks for your help

**Comment by julienvedebe** [comment]
I saw also an error in log : 

jinja2.exceptions.UndefinedError: 'value_json' is undefined

**Comment by julienvedebe** [comment]
Sorry issue was on my side (incorrect indent) I close the issue.

**Comment by pgorod** [comment]
Hi! Sorry, I was away on an Easter vacation, didn't get a chance to reply to you.

Anyway, I am glad it's solved! Cheers
